[colors.primary]
background = "#16161e"    # Mai închis decât originalul pentru mai mult contrast
foreground = "#c0caf5"    # Albastru-alb pentru text clar
dim_foreground = "#737aa2" # Text estompat

[colors.cursor]
text = "#16161e"
cursor = "#c0caf5"

[colors.vi_mode_cursor]
text = "#16161e" 
cursor = "#bb9af7"        # Violet pentru vi mode

[colors.search.matches]
foreground = "#16161e"
background = "#f7768e"    # Roz pentru matches

[colors.search.focused_match]
foreground = "#16161e"
background = "#e0af68"    # Galben pentru match-ul activ

[colors.hints.start]
foreground = "#16161e"
background = "#e0af68"

[colors.hints.end]
foreground = "#16161e"
background = "#f7768e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#c0caf5"
background = "#16161e"

[colors.selection]
text = "CellForeground"
background = "#364a82"    # Albastru închis pentru selecție

# Culori normale - Tokyo Night enhanced
[colors.normal]
black = "#15161e"         # Negru mai profund
red = "#f7768e"           # Roz-roșu vibrant (îmbunătățit)
green = "#9ece6a"         # Verde strălucitor
yellow = "#e0af68"        # Galben auriu cald
blue = "#7aa2f7"          # Albastru intens
magenta = "#bb9af7"       # Violet strălucitor
cyan = "#7dcfff"          # Cyan electric
white = "#a9b1d6"         # Alb-gri pentru text normal

# Culori strălucitoare - versiuni enhanced
[colors.bright]
black = "#414868"         # Gri pentru comentarii
red = "#ff7a93"           # Roșu mai strălucitor
green = "#b9f27c"         # Verde mai vibrant
yellow = "#ff9e64"        # Portocaliu-galben cald
blue = "#7da6ff"          # Albastru mai strălucitor
magenta = "#c0a7fa"       # Violet mai deschis
cyan = "#89ddff"          # Cyan mai intens
white = "#c0caf5"         # Alb pur pentru text important

[[colors.indexed_colors]]
index = 16
color = "#ff9e64"         # Portocaliu pentru constante

[[colors.indexed_colors]]
index = 17
color = "#db4b4b"         # Roșu închis pentru erori

